import { defineCollection, z } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';
import { LANGS } from './lib/langs.js';

export const lessonSchema = z.object({
  order: z.number().int(),
  difficulty: z.enum(['beginner', 'intermediate', 'advanced']),
  estimatedMinutes: z.number().int().min(2).max(12),
  viz: z.string().optional(),
  prerequisites: z.array(z.string()).default([]),
  languages: z.array(z.enum(LANGS)).default([]),
  problems: z.array(z.string()).default([]),
});

const baseSchema = docsSchema({ extend: lessonSchema });

/**
 * Makes this project's `order` actually drive the sidebar.
 *
 * Starlight's autogenerated sidebar sorts by its own `sidebar.order`, falling
 * back to alphabetical-by-slug. Nothing read `order`, so nav order was purely
 * alphabetical — which happened to match the teaching order only by luck, and
 * broke as soon as a lesson's number and its name disagreed (a lesson numbered
 * 222 rendered last, after 226 and 234).
 *
 * Rather than make authors write the same number twice, `order` is copied into
 * `sidebar.order` here, after parsing. An explicit `sidebar.order` in
 * frontmatter still wins, so Starlight's own field keeps working for anything
 * that is not a numbered lesson.
 */
export const collections = {
  docs: defineCollection({
    loader: docsLoader(),
    schema: (context) =>
      baseSchema(context).transform((data) => {
        if (typeof data.order !== 'number') return data;
        if (data.sidebar?.order !== undefined) return data;
        return { ...data, sidebar: { ...data.sidebar, order: data.order } };
      }),
  }),
};
