import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';

/*
 * The project's `order` frontmatter field is the teaching order, but Starlight's
 * autogenerated sidebar reads its own `sidebar.order` and otherwise falls back
 * to alphabetical-by-slug. For a while nothing bridged the two, so nav order
 * was alphabetical — which matched the teaching order only by coincidence and
 * broke as soon as a number and a name disagreed (a lesson numbered 222
 * rendered last, after 226 and 234). src/content.config.ts now copies `order`
 * into `sidebar.order` when parsing.
 *
 * The expected order is derived from the lesson files rather than hardcoded, so
 * this covers every lesson added later without anyone remembering to edit it.
 */
const contentRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../src/content/docs',
);

interface Lesson { slug: string; order: number }

function lessonsIn(group: string): Lesson[] {
  return readdirSync(join(contentRoot, group))
    .filter((f) => f.endsWith('.mdx') || f.endsWith('.md'))
    .map((file) => {
      const source = readFileSync(join(contentRoot, group, file), 'utf8');
      const match = /^order:\s*(-?\d+)\s*$/m.exec(source);
      if (!match) throw new Error(`${group}/${file} has no numeric "order" frontmatter`);
      return { slug: file.replace(/\.mdx?$/, ''), order: Number(match[1]) };
    })
    // Starlight breaks ties on order by sorting alphabetically by slug.
    .sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
}

for (const group of ['algorithms', 'complexity']) {
  test(`the ${group} sidebar follows the lessons' order field`, async ({ page }) => {
    const expected = lessonsIn(group);
    expect(expected.length).toBeGreaterThan(0);

    await page.goto(`/${group}/${expected[0]!.slug}/`);

    const rendered: string[] = [];
    for (const href of await page
      .locator(`nav a[href^="/${group}/"]`)
      .evaluateAll((links) => links.map((l) => l.getAttribute('href') ?? ''))) {
      const slug = href.replace(`/${group}/`, '').replace(/\/$/, '');
      if (slug && !rendered.includes(slug)) rendered.push(slug);
    }

    expect(rendered).toEqual(expected.map((l) => l.slug));
  });
}
